version: '3.7'
services:
  sentry:
    build: ./app
  
  nginx:
    image: docker.arvancloud.ir/nginx:alpine

  prometheus:
    image: docker.arvancloud.ir/prom/prometheus:v2.36.2
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention.time=60d'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/sentry.yml:/etc/prometheus/sentry.yml

    ports:
      - "9090:9090"

  alertmanager:
    image: docker.arvancloud.ir/prom/alertmanager:v0.24.0
    command:
      - "--config.file=/alertmanager.yml"
      - "--storage.path=/alertmanager"
    ports:
      - target: 9093
        published: 9093
        mode: host
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager.yml

volumes:
  prometheus_data:
