global:
  scrape_interval: 15s  # Set the scrape interval

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['172.19.0.1:8000']  # Replace with your FastAPI app address and port

rule_files:
  - './alertmanager/rules.yml'